---
- hosts: all
  name: Run linter
  tasks:
    - name: make lint
      make:
        target: lint
        chdir: "{{ zuul.project.src_dir }}"
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
