#!/bin/bash

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

declare FILES_MISSING_COPYRIGHT=()

# Find all files of given format and add license if missing
FILES=$(find -L . -type f \( -iname \*.go -o -iname \*.yaml -o -iname \*.yml -o -iname \*.sh -o -iname \*.ts -o -iname \*.css \) \
  -not -path "./etc" \
  -not -path "./client/dist/*" \
  -not -path "./client/node_modules/*" \
  -not -path "./tools/*node*" \
  | grep -v "testdata" \
  | grep -v "manifests")

for each in $FILES
do
  if ! grep -Eq 'Apache License|License-Identifier: Apache' $each
  then
    FILES_MISSING_COPYRIGHT+=($each)
  fi
done

if [ ${#FILES_MISSING_COPYRIGHT[@]} -gt 0 ]
then
   printf "Copyright header missing for: %s\n" "${FILES_MISSING_COPYRIGHT[@]}"
   echo "please run make add-copyright"
   exit 1
else
   echo "no file with missing copyright header detected, make target completed successfully"
fi

